# Generated by Django 5.0.3 on 2024-03-25 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phq_9', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='PHQResponse',
        ),
    ]
