# Generated by Django 5.0.3 on 2024-03-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phq_9', '0002_rename_response_phqresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='phqresponse',
            name='batch',
            field=models.IntegerField(default=1),
        ),
    ]
